[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "location/dist"
  
  # Directory to change to before starting a build
  base = "location"
  
  # Build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.19.0"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
